<?php

/**
 * @file
 * Main file for hooks and functions.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 * This hook must have link to it's definition.
 * You can press CTRL + Q to read this documentation right here.
 */
function dummy_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $messenger = \Drupal::messenger();
  $messenger->addMessage($form_id);
}

/**
 * Implements hook_form_FORM_ID_alter() for user_login_form.
 *
 * This hook only can be autocomplete, but not have link to documentation.
 */
function dummy_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['example'] = [
    '#markup' => t('Help'),
  ];
}

/**
 * Reverse string.
 *
 * @param string $text
 *   Text needs to be reversed.
 *
 * @return string
 *   A new string with reversed value.
 */
function dummy_example_custom_function($text) {
  return strrev($text);
}

/**
 * Implements hook_theme().
 */
function dummy_theme($existing, $type, $theme, $path) {
  return [
    'dummy_some_template' => [
      'variables' => [],
    ],
  ];
}
